## Q1_P1:

1.Use ‘vehicle_collisions’ data set.
2.For each month in 2016, find out the percentage of collisions in Manhattan out of that year's total accidents in New York City.
3.Display a few rows of the output use df.head().
4.Generate a csv output with four columns (‘Month’, ‘Manhattan’, ‘NYC’, ‘Percentage’)

In [1]:
import pandas as pd
from pandas import Series, DataFrame
import csv

In [3]:
df = pd.read_csv('E:/Python/Data_Assignment_3/vehicle_collisions.csv')

In [4]:
df.head()

,UNIQUE KEY,DATE,TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,LOCATION,ON STREET NAME,CROSS STREET NAME,...,VEHICLE 1 TYPE,VEHICLE 2 TYPE,VEHICLE 3 TYPE,VEHICLE 4 TYPE,VEHICLE 5 TYPE,VEHICLE 1 FACTOR,VEHICLE 2 FACTOR,VEHICLE 3 FACTOR,VEHICLE 4 FACTOR,VEHICLE 5 FACTOR
0,3146911,1/1/15,0:20,QUEENS,11358.0,40.751847,-73.787862,"(40.7518471, -73.787862)",47 AVENUE,193 STREET,...,SPORT UTILITY/STATION WAGON,NaN,NaN,NaN,NaN,TRAFFIC CONTROL DISREGARDED,NaN,NaN,NaN,NaN
1,3146180,1/1/15,0:20,NaN,NaN,40.771289,-73.946693,"(40.7712888, -73.9466928)",NaN,NaN,...,PASSENGER VEHICLE,NaN,NaN,NaN,NaN,ANIMALS ACTION,NaN,NaN,NaN,NaN
2,3146384,1/1/15,0:21,BROOKLYN,11205.0,40.689445,-73.955121,"(40.6894449, -73.9551212)",BEDFORD AVENUE,LAFAYETTE AVENUE,...,PASSENGER VEHICLE,UNKNOWN,NaN,NaN,NaN,FATIGUED/DROWSY,UNSPECIFIED,NaN,NaN,NaN
3,3146013,1/1/15,0:30,BROOKLYN,11213.0,40.673845,-73.925080,"(40.6738445, -73.9250801)",BUFFALO AVENUE,SAINT MARKS AVENUE,...,BUS,PASSENGER VEHICLE,NaN,NaN,NaN,LOST CONSCIOUSNESS,NaN,NaN,NaN,NaN
4,3146120,1/1/15,0:33,NaN,NaN,NaN,NaN,NaN,RICHMOND TERRACE,SOUTH AVENUE,...,UNKNOWN,PASSENGER VEHICLE,NaN,NaN,NaN,UNSPECIFIED,UNSPECIFIED,NaN,NaN,NaN

In [5]:
df['Year'] = pd.to_datetime(df['DATE']).dt.year # extracting the year of all the data 
df['Month'] = pd.to_datetime(df['DATE']).dt.month # extracting the month of the data

In [6]:
Year16 = df[df['Year']==2016] #extracting the data of the year 2016

In [46]:
Year16

,UNIQUE KEY,DATE,TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,LOCATION,ON STREET NAME,CROSS STREET NAME,...,VEHICLE 3 TYPE,VEHICLE 4 TYPE,VEHICLE 5 TYPE,VEHICLE 1 FACTOR,VEHICLE 2 FACTOR,VEHICLE 3 FACTOR,VEHICLE 4 FACTOR,VEHICLE 5 FACTOR,Year,Month
217539,3374565,1/1/16,0:01,MANHATTAN,10022.0,40.760223,-73.967462,"(40.7602226, -73.967462)",EAST 57 STREET,3 AVENUE,...,NaN,NaN,NaN,OTHER VEHICULAR,OTHER VEHICULAR,NaN,NaN,NaN,2016,1
217540,3511927,1/1/16,0:01,BROOKLYN,11235.0,NaN,NaN,NaN,EMMONS AVENUE,OCEAN AVENUE,...,NaN,NaN,NaN,UNSPECIFIED,UNSPECIFIED,NaN,NaN,NaN,2016,1
217541,3363408,1/1/16,0:01,MANHATTAN,10035.0,40.805057,-73.939034,"(40.8050573, -73.9390342)",EAST 125 STREET,PARK AVENUE,...,NaN,NaN,NaN,UNSPECIFIED,NaN,NaN,NaN,NaN,2016,1
217542,3364610,1/1/16,0:05,MANHATTAN,10035.0,40.799258,-73.939050,"(40.7992577, -73.9390504)",3 AVENUE,EAST 118 STREET,...,NaN,NaN,NaN,UNSPECIFIED,UNSPECIFIED,NaN,NaN,NaN,2016,1
217543,3363371,1/1/16,0:15,MANHATTAN,10011.0,40.738552,-73.999682,"(40.738552, -73.9996824)",7 AVENUE,WEST 14 STREET,...,NaN,NaN,NaN,LOST CONSCIOUSNESS,UNSPECIFIED,NaN,NaN,NaN,2016,1
217544,3363808,1/1/16,0:23,BROOKLYN,11207.0,40.653419,-73.888970,"(40.6534188, -73.88897)",GEORGIA AVENUE,COZINE AVENUE,...,NaN,NaN,NaN,DRIVER INATTENTION/DISTRACTION,UNSPECIFIED,NaN,NaN,NaN,2016,1
217545,3363916,1/1/16,0:25,QUEENS,11427.0,40.729034,-73.743863,"(40.7290337, -73.7438625)",89 AVENUE,SPRINGFIELD BOULEVARD,...,NaN,NaN,NaN,UNSPECIFIED,UNSPECIFIED,NaN,NaN,NaN,2016,1
217546,3363584,1/1/16,0:30,NaN,NaN,40.737556,-73.850881,"(40.7375562, -73.8508811)",NaN,NaN,...,NaN,NaN,NaN,TURNING IMPROPERLY,UNSPECIFIED,NaN,NaN,NaN,2016,1
217547,3363558,1/1/16,0:33,QUEENS,11419.0,40.684137,-73.824123,"(40.6841371, -73.8241226)",107 AVENUE,118 STREET,...,NaN,NaN,NaN,UNSPECIFIED,UNSPECIFIED,NaN,NaN,NaN,2016,1
217548,3363566,1/1/16,0:50,QUEENS,11417.0,40.681385,-73.847475,"(40.6813845, -73.8474752)",ROCKAWAY BOULEVARD,92 STREET,...,NaN,NaN,NaN,FAILURE TO YIELD RIGHT-OF-WAY,NaN,NaN,NaN,NaN,2016,1
217549,3370573,1/1/16,0:51,MANHATTAN,10040.0,40.863572,-73.926012,"(40.8635725, -73.9260124)",SHERMAN AVENUE,DYCKMAN STREET,...,NaN,NaN,NaN,OTHER VEHICULAR,LOST CONSCIOUSNESS,NaN,NaN,NaN,2016,1
217550,3364217,1/1/16,10:00,BROOKLYN,11207.0,40.675736,-73.896853,"(40.6757357, -73.8968533)",PENNSYLVANIA AVENUE,ATLANTIC AVENUE,...,NaN,NaN,NaN,ALCOHOL INVOLVEMENT,UNSPECIFIED,NaN,NaN,NaN,2016,1
217551,3363892,1/1/16,10:00,QUEENS,11435.0,40.693080,-73.803818,"(40.6930797, -73.8038184)",LIVERPOOL STREET,SOUTH ROAD,...,NaN,NaN,NaN,UNSPECIFIED,UNSPECIFIED,NaN,NaN,NaN,2016,1
217552,3363749,1/1/16,10:00,BROOKLYN,11224.0,40.580379,-73.967600,"(40.5803795, -73.9676001)",OCEAN PARKWAY,NEPTUNE AVENUE,...,NaN,NaN,NaN,UNSPECIFIED,UNSPECIFIED,NaN,NaN,NaN,2016,1
217553,3363931,1/1/16,10:00,QUEENS,11101.0,40.744733,-73.933589,"(40.7447332, -73.9335895)",VANDAM STREET,THOMSON AVENUE,...,NaN,NaN,NaN,DRIVER INATTENTION/DISTRACTION,UNSPECIFIED,NaN,NaN,NaN,2016,1
217554,3363475,1/1/16,10:17,BRONX,10468.0,40.876976,-73.889660,"(40.876976, -73.8896598)",PAUL AVENUE,WEST 205 STREET,...,PASSENGER VEHICLE,SPORT UTILITY/STATION WAGON,NaN,DRIVER INATTENTION/DISTRACTION,UNSPECIFIED,UNSPECIFIED,UNSPECIFIED,NaN,2016,1
217555,3363579,1/1/16,10:20,QUEENS,11373.0,40.736643,-73.865831,"(40.7366431, -73.8658311)",57 AVENUE,JUNCTION BOULEVARD,...,NaN,NaN,NaN,UNSPECIFIED,UNSPECIFIED,NaN,NaN,NaN,2016,1
217556,3363903,1/1/16,10:30,QUEENS,11385.0,40.710967,-73.916003,"(40.7109667, -73.9160027)",WOODWARD AVENUE,WILLOUGHBY AVENUE,...,NaN,NaN,NaN,UNSPECIFIED,UNSPECIFIED,NaN,NaN,NaN,2016,1
217557,3417381,1/1/16,10:30,BROOKLYN,11210.0,40.635610,-73.951882,"(40.6356103, -73.9518823)",NaN,NaN,...,NaN,NaN,NaN,BACKING UNSAFELY,BACKING UNSAFELY,NaN,NaN,NaN,2016,1
217558,3364239,1/1/16,10:30,BROOKLYN,11216.0,40.680390,-73.949557,"(40.6803904, -73.949557)",NOSTRAND AVENUE,FULTON STREET,...,NaN,NaN,NaN,UNSPECIFIED,UNSPECIFIED,NaN,NaN,NaN,2016,1
217559,3364001,1/1/16,10:30,NaN,NaN,40.621250,-74.168876,"(40.6212504, -74.1688765)",NaN,NaN,...,NaN,NaN,NaN,TURNING IMPROPERLY,UNSPECIFIED,NaN,NaN,NaN,2016,1
217560,3363682,1/1/16,10:40,BRONX,10455.0,40.812666,-73.906330,"(40.8126657, -73.90633)",EAST 149 STREET,TINTON AVENUE,...,SPORT UTILITY/STATION WAGON,NaN,NaN,UNSPECIFIED,UNSPECIFIED,UNSPECIFIED,NaN,NaN,2016,1
217561,3363819,1/1/16,10:55,BROOKLYN,11213.0,40.668950,-73.933888,"(40.6689504, -73.9338885)",EASTERN PARKWAY,SCHENECTADY AVENUE,...,PASSENGER VEHICLE,NaN,NaN,UNSPECIFIED,UNSPECIFIED,UNSPECIFIED,NaN,NaN,2016,1
217562,3363402,1/1/16,11:00,NaN,NaN,40.781937,-73.944271,"(40.7819374, -73.9442713)",NaN,NaN,...,TAXI,NaN,NaN,TURNING IMPROPERLY,UNSPECIFIED,UNSPECIFIED,NaN,NaN,2016,1
217563,3363995,1/1/16,11:10,QUEENS,11370.0,40.763053,-73.886730,"(40.7630535, -73.8867296)",82 STREET,25 AVENUE,...,NaN,NaN,NaN,ALCOHOL INVOLVEMENT,NaN,NaN,NaN,NaN,2016,1
217564,3363377,1/1/16,11:27,MANHATTAN,10010.0,40.738797,-73.977147,"(40.7387967, -73.977147)",1 AVENUE,EAST 26 STREET,...,TAXI,NaN,NaN,ILLNESS,DRIVER INATTENTION/DISTRACTION,UNSPECIFIED,NaN,NaN,2016,1
217565,3363508,1/1/16,11:30,BROOKLYN,11209.0,40.614814,-74.029402,"(40.6148138, -74.0294019)",95 STREET,FORT HAMILTON PARKWAY,...,NaN,NaN,NaN,UNSPECIFIED,UNSPECIFIED,NaN,NaN,NaN,2016,1
217566,3363357,1/1/16,11:30,MANHATTAN,10013.0,40.725673,-74.005780,"(40.7256734, -74.0057798)",VARICK STREET,SPRING STREET,...,NaN,NaN,NaN,PRESCRIPTION MEDICATION,UNSPECIFIED,NaN,NaN,NaN,2016,1
217567,3363422,1/1/16,11:40,BRONX,10459.0,40.818890,-73.896082,"(40.8188902, -73.8960823)",INTERVALE AVENUE,BECK STREET,...,NaN,NaN,NaN,UNSPECIFIED,UNSPECIFIED,NaN,NaN,NaN,2016,1
217568,3364419,1/1/16,11:40,QUEENS,11102.0,40.772699,-73.932684,"(40.7726989, -73.9326843)",ASTORIA BOULEVARD,8 STREET,...,NaN,NaN,NaN,PHYSICAL DISABILITY,UNSPECIFIED,NaN,NaN,NaN,2016,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
445114,3593935,12/31/16,6:49,NaN,NaN,NaN,NaN,NaN,MONTAUK AVENUE,NaN,...,NaN,NaN,NaN,DRIVER INATTENTION/DISTRACTION,UNSPECIFIED,NaN,NaN,NaN,2016,12
445115,3590463,12/31/16,6:50,BROOKLYN,11217.0,40.683514,-73.975951,"(40.6835142, -73.9759509)",ATLANTIC AVENUE,FORT GREENE PLACE,...,NaN,NaN,NaN,FAILURE TO YIELD RIGHT-OF-WAY,UNSPECIFIED,NaN,NaN,NaN,2016,12
445116,3589645,12/31/16,7:00,QUEENS,11357.0,40.789224,-73.804571,"(40.7892244, -73.8045715)",NaN,NaN,...,SPORT UTILITY/STATION WAGON,NaN,NaN,DRIVER INATTENTION/DISTRACTION,UNSPECIFIED,UNSPECIFIED,NaN,NaN,2016,12
445117,3590483,12/31/16,7:15,BROOKLYN,11237.0,40.704208,-73.914569,"(40.704208, -73.9145686)",NaN,NaN,...,NaN,NaN,NaN,UNSPECIFIED,NaN,NaN,NaN,NaN,2016,12
445118,3589740,12/31/16,7:30,NaN,NaN,NaN,NaN,NaN,HEATH AVENUE,BAILEY AVENUE,...,NaN,NaN,NaN,UNSPECIFIED,NaN,NaN,NaN,NaN,2016,12
445119,3590868,12/31/16,7:45,NaN,NaN,NaN,NaN,NaN,1 AVENUE,NaN,...,NaN,NaN,NaN,OUTSIDE CAR DISTRACTION,UNSPECIFIED,NaN,NaN,NaN,2016,12
445120,3589646,12/31/16,7:48,NaN,NaN,NaN,NaN,NaN,WEST 10 STREET,NaN,...,NaN,NaN,NaN,UNSPECIFIED,UNSPECIFIED,NaN,NaN,NaN,2016,12
445121,3590765,12/31/16,7:51,MANHATTAN,10128.0,40.782736,-73.955336,"(40.7827364, -73.9553364)",EAST 90 STREET,PARK AVENUE,...,SPORT UTILITY/STATION WAGON,SPORT UTILITY/STATION WAGON,NaN,ALCOHOL INVOLVEMENT,UNSPECIFIED,UNSPECIFIED,UNSPECIFIED,NaN,2016,12
445122,3590354,12/31/16,8:00,BROOKLYN,11221.0,40.692148,-73.919459,"(40.6921483, -73.9194594)",GATES AVENUE,EVERGREEN AVENUE,...,NaN,NaN,NaN,TRAFFIC CONTROL DISREGARDED,UNSPECIFIED,NaN,NaN,NaN,2016,12
445123,3590090,12/31/16,8:14,BROOKLYN,11226.0,40.645722,-73.958073,"(40.6457217, -73.9580731)",NaN,NaN,...,NaN,NaN,NaN,UNSPECIFIED,UNSPECIFIED,NaN,NaN,NaN,2016,12
445124,3590129,12/31/16,8:35,BRONX,10466.0,40.890918,-73.858760,"(40.8909183, -73.8587599)",NaN,NaN,...,NaN,NaN,NaN,UNSPECIFIED,NaN,NaN,NaN,NaN,2016,12
445125,3594298,12/31/16,8:35,BROOKLYN,11203.0,40.660656,-73.930321,"(40.6606563, -73.9303212)",RUTLAND ROAD,EAST 51 STREET,...,SPORT UTILITY/STATION WAGON,NaN,NaN,OTHER VEHICULAR,UNSPECIFIED,UNSPECIFIED,NaN,NaN,2016,12
445126,3589868,12/31/16,8:35,NaN,NaN,40.740844,-73.726796,"(40.7408436, -73.7267962)",NaN,NaN,...,NaN,NaN,NaN,DRIVER INATTENTION/DISTRACTION,UNSPECIFIED,NaN,NaN,NaN,2016,12
445127,3589719,12/31/16,9:00,BROOKLYN,11206.0,40.703864,-73.938333,"(40.7038636, -73.9383333)",NaN,NaN,...,NaN,NaN,NaN,DRIVER INATTENTION/DISTRACTION,UNSPECIFIED,NaN,NaN,NaN,2016,12
445128,3590014,12/31/16,9:00,NaN,NaN,NaN,NaN,NaN,125 STREET,NaN,...,NaN,NaN,NaN,UNSPECIFIED,NaN,NaN,NaN,NaN,2016,12
445129,3592359,12/31/16,9:00,QUEENS,11368.0,40.743231,-73.866042,"(40.7432307, -73.8660416)",NaN,NaN,...,NaN,NaN,NaN,ALCOHOL INVOLVEMENT,UNSPECIFIED,NaN,NaN,NaN,2016,12
445130,3590562,12/31/16,9:00,BROOKLYN,11210.0,40.629480,-73.944469,"(40.6294805, -73.9444689)",NEW YORK AVENUE,AVENUE I,...,NaN,NaN,NaN,UNSPECIFIED,NaN,NaN,NaN,NaN,2016,12
445131,3590893,12/31/16,9:00,NaN,NaN,NaN,NaN,NaN,WILLOUGHBY AVENUE,NaN,...,NaN,NaN,NaN,OTHER VEHICULAR,OTHER VEHICULAR,NaN,NaN,NaN,2016,12
445132,3589936,12/31/16,9:00,BRONX,10456.0,40.827911,-73.904195,"(40.8279109, -73.9041947)",NaN,NaN,...,NaN,NaN,NaN,UNSAFE SPEED,NaN,NaN,NaN,NaN,2016,12
445133,3590948,12/31/16,9:00,BROOKLYN,11201.0,40.701359,-73.982851,"(40.7013592, -73.982851)",YORK STREET,GOLD STREET,...,NaN,NaN,NaN,ILLNESS,UNSPECIFIED,NaN,NaN,NaN,2016,12
445134,3589741,12/31/16,9:15,NaN,NaN,NaN,NaN,NaN,EAST 196 STREET,NaN,...,NaN,NaN,NaN,UNSPECIFIED,UNSPECIFIED,NaN,NaN,NaN,2016,12
445135,3589873,12/31/16,9:15,QUEENS,11422.0,40.662657,-73.732998,"(40.6626567, -73.7329976)",FRANCIS LEWIS BOULEVARD,249 STREET,...,NaN,NaN,NaN,UNSPECIFIED,UNSPECIFIED,NaN,NaN,NaN,2016,12
445136,3589884,12/31/16,9:30,QUEENS,11367.0,40.717301,-73.825143,"(40.717301, -73.8251426)",NaN,NaN,...,NaN,NaN,NaN,UNSPECIFIED,NaN,NaN,NaN,NaN,2016,12
445137,3590072,12/31/16,9:35,NaN,NaN,NaN,NaN,NaN,HILLSIDE AVENUE,202 STREET,...,NaN,NaN,NaN,DRIVER INATTENTION/DISTRACTION,DRIVER INATTENTION/DISTRACTION,NaN,NaN,NaN,2016,12
445138,3590467,12/31/16,9:35,BROOKLYN,11235.0,NaN,NaN,NaN,EAST 16 STREET,SHEEPSHEAD BAY ROAD,...,NaN,NaN,NaN,UNSPECIFIED,NaN,NaN,NaN,NaN,2016,12
445139,3589785,12/31/16,9:37,QUEENS,11355.0,40.755958,-73.828517,"(40.7559578, -73.828517)",NaN,NaN,...,NaN,NaN,NaN,UNSPECIFIED,NaN,NaN,NaN,NaN,2016,12
445140,3593758,12/31/16,9:40,BROOKLYN,11225.0,40.669114,-73.953354,"(40.6691137, -73.9533541)",ROGERS AVENUE,UNION STREET,...,NaN,NaN,NaN,PASSING OR LANE USAGE IMPROPER,UNSPECIFIED,NaN,NaN,NaN,2016,12
445141,3589918,12/31/16,9:50,NaN,NaN,NaN,NaN,NaN,JESUP AVENUE,NaN,...,NaN,NaN,NaN,UNSPECIFIED,UNSPECIFIED,NaN,NaN,NaN,2016,12
445142,3590568,12/31/16,9:55,BRONX,10462.0,40.835210,-73.854972,"(40.8352098, -73.8549717)",UNIONPORT ROAD,OLMSTEAD AVENUE,...,NaN,NaN,NaN,TRAFFIC CONTROL DISREGARDED,DRIVER INATTENTION/DISTRACTION,NaN,NaN,NaN,2016,12
445143,3589858,12/31/16,9:56,NaN,NaN,NaN,NaN,NaN,2 AVENUE,NaN,...,NaN,NaN,NaN,DRIVER INATTENTION/DISTRACTION,DRIVER INATTENTION/DISTRACTION,NaN,NaN,NaN,2016,12

In [47]:
ManhCountList=[]
ManhList=[]
PercList=[]
NYCList =[]

for i in range(1, 13):

    Month16 = Year16[Year16['Month']==i]
    TotalCount = Year16[Year16['Month']==i].count().Month
    Manhcount = Month16[Month16['BOROUGH']=='MANHATTAN'].count().BOROUGH
    Percent = Manhcount/TotalCount
    ManhList.append(i)
    ManhCountList.append(Manhcount)
    NYCList.append(TotalCount)   
    PercList.append(Percent)

In [48]:
final = {'MONTH':ManhList,'MANHATTAN':ManhCountList,'NYC':NYCList,'PERCENTAGE':PercList}
df2 = DataFrame(final)

In [49]:
df2.head()

   MANHATTAN  MONTH    NYC  PERCENTAGE
0       3178      1  18101    0.175570
1       3195      2  15985    0.199875
2       3479      3  18471    0.188349
3       3540      4  18331    0.193115
4       3432      5  20052    0.171155

In [50]:
df2.to_csv('Q1_P1_output.csv')